"""Python SDK for authorizer.dev — self-hosted authentication & authorization."""

from __future__ import annotations

from .async_client import AsyncAuthorizerClient
from .client import AuthorizerClient
from .exceptions import AuthorizerConnectionError, AuthorizerError
from .types import (
    AuthToken,
    CheckPermissionsRequest,
    CheckPermissionsResponse,
    FgaTupleInput,
    ForgotPasswordRequest,
    ForgotPasswordResponse,
    GenericResponse,
    GetTokenRequest,
    GetTokenResponse,
    ListPermissionsRequest,
    ListPermissionsResponse,
    LoginRequest,
    MagicLinkLoginRequest,
    MetaData,
    OAuthProviders,
    Permission,
    PermissionCheckInput,
    PermissionCheckResult,
    ResendOTPRequest,
    ResendVerifyEmailRequest,
    ResetPasswordRequest,
    ResponseTypes,
    RevokeTokenRequest,
    SessionQueryRequest,
    SignUpRequest,
    TokenType,
    UpdateProfileRequest,
    User,
    ValidateJWTTokenRequest,
    ValidateJWTTokenResponse,
    ValidateSessionRequest,
    ValidateSessionResponse,
    VerifyEmailRequest,
    VerifyOTPRequest,
)

__version__ = "0.1.0"

__all__ = [
    "AuthorizerClient",
    "AsyncAuthorizerClient",
    "AuthorizerError",
    "AuthorizerConnectionError",
    "AuthToken",
    "CheckPermissionsRequest",
    "CheckPermissionsResponse",
    "FgaTupleInput",
    "ForgotPasswordRequest",
    "ForgotPasswordResponse",
    "GenericResponse",
    "GetTokenRequest",
    "GetTokenResponse",
    "ListPermissionsRequest",
    "ListPermissionsResponse",
    "LoginRequest",
    "MagicLinkLoginRequest",
    "MetaData",
    "OAuthProviders",
    "Permission",
    "PermissionCheckInput",
    "PermissionCheckResult",
    "ResendOTPRequest",
    "ResendVerifyEmailRequest",
    "ResetPasswordRequest",
    "ResponseTypes",
    "RevokeTokenRequest",
    "SessionQueryRequest",
    "SignUpRequest",
    "TokenType",
    "UpdateProfileRequest",
    "User",
    "ValidateJWTTokenRequest",
    "ValidateJWTTokenResponse",
    "ValidateSessionRequest",
    "ValidateSessionResponse",
    "VerifyEmailRequest",
    "VerifyOTPRequest",
    "__version__",
]
